export const APP_WRITE_ID = 'my-crm-system-nuxt'
export const DB_ID = 'crm-base'
export const STORAGE_ID = 'storage'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CASTOMERS = 'customer'
export const COLLECTION_COMMENTS = 'comments'
